version: "3.9"
services:
  db:
    container_name: serv_db
    image: postgres:14.3-alpine
    restart: always
    environment:
           - POSTGRES_DB=${POSTGRES_DB}
           - POSTGRES_USER=${POSTGRES_USER}
           - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
        - db_data:/var/lib/postgresql/data

  bot:
        container_name: serv_bot
        build: .
        command: sh -c "alembic upgrade head && python -m main"
        restart: on-failure
        env_file: ./.env
        depends_on:
          - db

  
volumes:
    db_data: