"""First migration

Revision ID: 93e57b799ae7
Revises: 
Create Date: 2023-01-27 23:05:32.796459

"""
import os

import sqlalchemy as sa
from dotenv import load_dotenv

from alembic import op

load_dotenv(".env")

# revision identifiers, used by Alembic.
revision = "93e57b799ae7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.Column("doc_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_type_id"],
            ["document_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        f"INSERT INTO users (id, created_at, name, is_staff, telegram_id) VALUES (1, NOW(), 'Admin', TRUE, {os.environ['ADMIN_ID']})"
    )
    op.execute(
        "INSERT INTO document_types (id, created_at, name) VALUES (1, NOW(), 'regulations')"
    )
    op.execute(
        "INSERT INTO document_types (id, created_at, name) VALUES (2, NOW(), 'acts')"
    )
    op.execute(
        "INSERT INTO document_types (id, created_at, name) VALUES (3, NOW(), 'instructions')"
    )
    op.execute(
        "INSERT INTO document_types (id, created_at, name) VALUES (4, NOW(), 'drivers')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    op.drop_table("users")
    op.drop_table("document_types")
    # ### end Alembic commands ###
